# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "/data/theo/torchtitan-dumps"
description = "Llama 3 1B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
disable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true
save_for_all_ranks = false

[model]
name = "llama3"
flavor = "test_1b"
hf_assets_path = "/home/theo/training-tt/torchtitan/assets/hf/Llama-3.2-1B"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 200  # lr scheduler warm up

[training]
local_batch_size = 16
seq_len = 2048
max_norm = 1.0  # grad norm clipping
steps = 1000
dataset = "c4_local"

[parallelism]
data_parallel_replicate_degree = 4
data_parallel_shard_degree = 8
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = true
folder = "/data/theo/torchtitan-checkpoints/test-torchtitan-ter"
interval = 50
last_save_model_only = true
export_dtype = "bfloat16"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[compile]
enable=false
components = ["model", "loss"]

[activation_checkpoint]
mode = "none"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]

[validation]
enable = false
dataset = "c4_validation"
freq = 500
steps = 1200 # Recommend value for c4_validation with world-size=8 and seq_len=8192
